// This file was generated by a custom prisma generator, do not edit manually.
export const TaskStatus = {
  todo: "todo",
  in_progress: "in_progress",
  done: "done",
  canceled: "canceled",
} as const;

export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];

export const TaskLabel = {
  bug: "bug",
  feature: "feature",
  enhancement: "enhancement",
  documentation: "documentation",
} as const;

export type TaskLabel = (typeof TaskLabel)[keyof typeof TaskLabel];

export const TaskPriority = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;

export type TaskPriority = (typeof TaskPriority)[keyof typeof TaskPriority];
